Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  class_num: 102
  save_interval: 1
  eval_mode: "retrieval"
  eval_during_train: True
  eval_interval: 1
  epochs: 20
  print_batch_step: 10
  use_visualdl: False
  image_shape: [3, 224, 224]

  #inference related
  save_inference_dir: "./inference"

Arch:
  name: "RecModel"
  infer_output_key:  "features"
  infer_add_softmax: "false"
  Backbone:
    name: "ResNet50_vd"
    pretrained: False
  BackboneStopLayer: 
    name: "flatten_0"
    output_dim: 2048
  Head:
    name: "FC"
    class_num: 102
    embedding_size: 2048

Loss:
  Train:
    - CELoss:
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Piecewise
    learning_rate: 0.1
    decay_epochs: [30, 60, 90]
    values: [0.1, 0.01, 0.001, 0.0001]
  regularizer:
    name: 'L2'
    coeff: 0.0001

DataLoader:
  Train:
    dataset:
        name: ImageNetDataset
        image_root:  "./dataset/flowers102/"
        cls_label_path:  "./dataset/flowers102/train_list.txt"
        transform_ops:
          - RandCropImage:
              size: 224
          - RandFlipImage:
              flip_code: 1
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
    sampler:
        name: DistributedBatchSampler
        batch_size: 256
        drop_last: False
        shuffle: True
    loader:
        num_workers: 6
        use_shared_memory: False
  
  Eval:
    Query:
      dataset: 
          name: ImageNetDataset
          image_root: "./dataset/flowers102/"
          cls_label_path: "./dataset/flowers102/val_list.txt"
          transform_ops:
            - ResizeImage:
                resize_short: 256
            - CropImage:
                size: 224
            - NormalizeImage:
                scale: 0.00392157
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
                order: ''
      sampler:
          name: DistributedBatchSampler
          batch_size: 512
          drop_last: False
          shuffle: False
      loader:
          num_workers: 6
          use_shared_memory: True

    Gallery:
      dataset: 
          name: ImageNetDataset
          image_root: "./dataset/flowers102/"
          cls_label_path: "./dataset/flowers102/train_list.txt"
          transform_ops:
            - ResizeImage:
                resize_short: 256
            - CropImage:
                size: 224
            - NormalizeImage:
                scale: 0.00392157
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
                order: ''
      sampler:
          name: DistributedBatchSampler
          batch_size: 512
          drop_last: False
          shuffle: False
      loader:
          num_workers: 6
          use_shared_memory: True

Metric:
    Train:
    - TopkAcc:
        topk: [1, 5]
    Eval:
    - Recallk:
        topk: [1, 10]
    
