Global:
  infer_imgs: "./dataset/product_demo_data_v1.0/query"
  det_inference_model_dir: "./models/ppyolov2_r50vd_dcn_mainbody_v1.0_infer"
  rec_inference_model_dir: "./models/product_ResNet50_vd_aliproduct_v1.0_infer"
  batch_size: 1
  image_shape: [3, 640, 640]
  threshold: 0.2
  max_det_results: 2
  labe_list:
  - foreground

  # inference engine config
  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 100
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

DetPreProcess:
  transform_ops:
    - DetResize:
        interp: 2
        keep_ratio: false
        target_size: [640, 640]
    - DetNormalizeImage:
        is_scale: true
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - DetPermute: {}
DetPostProcess: {}

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

RecPostProcess: null

# indexing engine config
IndexProcess:
  index_path: "./dataset/product_demo_data_v1.0/index"
  search_budget: 100
  return_k: 5
  dist_type: "IP"
